---
# file: local.yml
#   Short-cut to run local install tasks without setting up an inventory.
#
# Run roles locally via following command:
#   ansible-playbook -i localhost, local.yml [-e var=val]* --tags=<tag[,tag]> --skip-tags=<tag[,tag]>
- hosts: localhost
  connection: local
  vars:
    postgresql_version: 11
    postgresql_flavor: "pgdg"
    postgresql_conf:
      listen_addresses: "'*'"
      hba_file: "'/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf'"
      ident_file: "'/etc/postgresql/{{ postgresql_version }}/main/pg_ident.conf'"
  roles:
    - '.' # The current directory itself is the role
